import { WebsiteSettings, FileItem, CategoryItem, SocialLinkItem } from '../types';

export const DEFAULT_SETTINGS: WebsiteSettings = {
  storeName: 'NOVA FILE STORE',
  logoUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=300&auto=format&fit=crop&q=80',
  description: 'Verified Direct Downloads & Fast Utilities. All files scanned & tested safe.',
  username: '@novastore_official',
  socialLink: 'https://t.me',
  telegramLink: 'https://t.me',
  footerText: '© 2026 Nova File Store. All rights reserved. Fast & secure downloads.',
  browserTitle: 'Nova File Store - Direct Downloads',
  faviconUrl: '',
  primaryColor: '#facc15',
  backgroundColor: '#09090b',
  textColor: '#ffffff',
  borderColor: '#eab308',
  buttonRadius: 'rounded-xl',
  glowIntensity: 'normal',
  fontFamily: 'Outfit',
  cardStyle: 'bordered',
  websiteStatus: 'live',
  maintenanceMessage: 'We are currently performing scheduled server upgrades. Please check back shortly or join our Telegram channel for live updates.',
  // Homepage Banner
  bannerEnabled: true,
  bannerTitle: '🚀 Download Verified VIP Android & PC Tools',
  bannerSubtitle: 'All links tested malware-free. Direct high-speed download mirrors with zero popups.',
  bannerImageUrl: '',
  bannerButtonText: 'Join Official Telegram',
  bannerButtonLink: 'https://t.me',
  // Announcement
  announcementEnabled: true,
  announcementText: '🔥 New Ultra FPS Game Booster v4.2 released! Check out the Gaming Tools section for high-speed download links.',
  announcementLink: 'https://t.me',
  announcementType: 'info',
  // Monetization & Ads
  monetizationEnabled: false,
  vipGatingEnabled: true,
  adHeaderEnabled: false,
  adHeaderCode: '',
  adInfeedEnabled: false,
  adInfeedCode: '',
  adFooterEnabled: false,
  adFooterCode: '',
  vipInstructions: 'To activate VIP access, send a message to @novastore_admin on Telegram with your email address or transaction screenshot.',
  updatedAt: new Date().toISOString(),
};

export const DEFAULT_CATEGORIES: CategoryItem[] = [
  { id: 'cat-android', name: 'Android Tools', displayOrder: 1 },
  { id: 'cat-gaming', name: 'Gaming Tools', displayOrder: 2 },
  { id: 'cat-pc', name: 'PC Utilities', displayOrder: 3 },
  { id: 'cat-mods', name: 'Premium Mods', displayOrder: 4 },
  { id: 'cat-docs', name: 'Documents & Guides', displayOrder: 5 },
];

export const DEFAULT_FILES: FileItem[] = [
  {
    id: 'file-1',
    name: 'Android System Optimizer Pro',
    url: 'https://github.com',
    description: 'High-speed cache cleaning and performance booster for all Android 10+ devices.',
    categoryId: 'cat-android',
    categoryName: 'Android Tools',
    icon: 'fa-brands fa-android',
    status: 'active',
    displayOrder: 1,
    clicks: 1420,
    views: 3820,
    isFeatured: true,
    isPremium: false,
    fileSize: '18.4 MB',
    version: 'v3.2.0',
    mirrors: [
      { label: 'Cloud Drive Mirror', url: 'https://drive.google.com' },
      { label: 'Telegram Direct APK', url: 'https://t.me' },
    ],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'file-2',
    name: 'Ultra FPS Game Booster v4.2',
    url: 'https://github.com',
    description: 'Unlock 90/120 FPS configs, reduce touch latency, and stabilize framerates.',
    categoryId: 'cat-gaming',
    categoryName: 'Gaming Tools',
    icon: 'fa-solid fa-gamepad',
    status: 'active',
    displayOrder: 2,
    clicks: 2890,
    views: 6410,
    isFeatured: true,
    isPremium: false,
    fileSize: '24.1 MB',
    version: 'v4.2.1',
    mirrors: [
      { label: 'Direct Fast Server', url: 'https://github.com' },
      { label: 'MediaFire Mirror', url: 'https://mediafire.com' },
    ],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'file-3',
    name: 'Universal USB Firmware Flasher',
    url: 'https://github.com',
    description: 'One-click ROM installation and recovery backup utility for PC.',
    categoryId: 'cat-pc',
    categoryName: 'PC Utilities',
    icon: 'fa-solid fa-microchip',
    status: 'active',
    displayOrder: 3,
    clicks: 980,
    views: 2150,
    isFeatured: false,
    isPremium: true,
    fileSize: '85.6 MB',
    version: 'v1.9.0',
    mirrors: [
      { label: 'Mega Mirror', url: 'https://mega.nz' },
    ],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'file-4',
    name: 'Network Speed Radar & Ping Fixer',
    url: 'https://github.com',
    description: 'Low-latency DNS routing script and connection stability diagnostic tool.',
    categoryId: 'cat-android',
    categoryName: 'Android Tools',
    icon: 'fa-solid fa-wifi',
    status: 'active',
    displayOrder: 4,
    clicks: 1650,
    views: 3120,
    isFeatured: false,
    isPremium: false,
    fileSize: '12.8 MB',
    version: 'v2.0.4',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'file-5',
    name: 'Premium Modded UI Theme Pack',
    url: 'https://github.com',
    description: 'Dark cyber neon icons, luxury yellow widgets, and custom lockscreens.',
    categoryId: 'cat-mods',
    categoryName: 'Premium Mods',
    icon: 'fa-solid fa-palette',
    status: 'active',
    displayOrder: 5,
    clicks: 740,
    views: 1940,
    isFeatured: false,
    isPremium: true,
    fileSize: '42.0 MB',
    version: 'v5.0',
    mirrors: [
      { label: 'VIP Telegram Direct', url: 'https://t.me' },
    ],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'file-6',
    name: 'VIP Setup & Installation Manual PDF',
    url: 'https://github.com',
    description: 'Step-by-step PDF manual with troubleshooting steps and license keys guide.',
    categoryId: 'cat-docs',
    categoryName: 'Documents & Guides',
    icon: 'fa-solid fa-file-pdf',
    status: 'active',
    displayOrder: 6,
    clicks: 530,
    views: 1280,
    isFeatured: false,
    isPremium: false,
    fileSize: '4.2 MB',
    version: '2026 Edition',
    createdAt: new Date().toISOString(),
  },
];

export const DEFAULT_SOCIALS: SocialLinkItem[] = [
  {
    id: 'telegram',
    platform: 'Telegram',
    url: 'https://t.me',
    icon: 'fa-brands fa-telegram',
    enabled: true,
    displayOrder: 1,
  },
  {
    id: 'youtube',
    platform: 'YouTube',
    url: 'https://youtube.com',
    icon: 'fa-brands fa-youtube',
    enabled: true,
    displayOrder: 2,
  },
  {
    id: 'tiktok',
    platform: 'TikTok',
    url: 'https://tiktok.com',
    icon: 'fa-brands fa-tiktok',
    enabled: true,
    displayOrder: 3,
  },
  {
    id: 'whatsapp',
    platform: 'WhatsApp',
    url: 'https://whatsapp.com',
    icon: 'fa-brands fa-whatsapp',
    enabled: true,
    displayOrder: 4,
  },
  {
    id: 'facebook',
    platform: 'Facebook',
    url: 'https://facebook.com',
    icon: 'fa-brands fa-facebook',
    enabled: false,
    displayOrder: 5,
  },
  {
    id: 'instagram',
    platform: 'Instagram',
    url: 'https://instagram.com',
    icon: 'fa-brands fa-instagram',
    enabled: false,
    displayOrder: 6,
  },
];
